linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3

linters:
  disable-all: true
  enable:
    - dupl
    - gocritic
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - gosec
    - ineffassign
    - misspell
    - staticcheck
    - sqlclosecheck
    - unused

run:
  timeout: 10m

issues:
  # Show only new issues created after git revision: 02270a6
  new-from-rev: d108866
