Database:
  DSN: postgres://postgres:odyseeteam@host.docker.internal/uploads?sslmode=disable
  DBName: uploads
  AutoMigrations: true

RedisLocker: redis://:odyredis@host.docker.internal:6379/1

# ForkliftRequestsConnURL is Redis database where forklift will be listening for complete uploads requests.
ForkliftRequestsConnURL: redis://:odyredis@host.docker.internal:6379/4

PublicKeyURL: https://api.na-backend.dev.odysee.com/api/v1/asynqueries/auth/pubkey

Storage:
  Endpoint: http://host.docker.internal:9002
  Region: us-east-1
  Bucket: uploads
  Key: minio
  Secret: minio123
  Minio: true

CORSDomains:
  - http://*
  - https://*

GracefulShutdown: 3s
