Database:
  DSN: postgres://postgres:odyseeteam@localhost/uploads?sslmode=disable
  DBName: uploads
  AutoMigrations: true

RedisBus: redis://:odyredis@localhost:6379/1

IncomingStorage:
  Endpoint: http://localhost:9002
  Region: us-east-1
  Bucket: uploads
  Key: minio
  Secret: minio123
  Minio: true

ReflectorStorage:
  DatabaseDSN: 'user:password@tcp(host.com)/blobs'
  Region: us-east-1
  Bucket: blobs'
  Key: key
  Secret: secret

Concurrency: 10
BlobPath: /tmp/blobs
UploadPath: /tmp/uploads
