Database:
  DSN: postgres://postgres:odyseeteam@localhost/uploads?sslmode=disable
  DBName: uploads
  AutoMigrations: true

# ForkliftRequestsConnURL is Redis database where forklift will be listening for complete uploads requests.
# It corresponds to ForkliftRequestsConnURL in uploads.yml config.
ForkliftRequestsConnURL: redis://:odyredis@host.docker.internal:6379/4
# AsynqueryRequestsConnURL is Redis database where asynquery will be listening for finalized uploads requests.
AsynqueryRequestsConnURL: redis://:odyredis@host.docker.internal:6379/3

IncomingStorage:
  Endpoint: http://localhost:9002
  Region: us-east-1
  Bucket: uploads
  Key: minio
  Secret: minio123
  Flavor: minio

ReflectorStorage:
  DatabaseDSN: 'user:password@tcp(host.com)/blobs'
  Region: us-east-1
  Bucket: blobs'
  Key: key
  Secret: secret

Concurrency: 10
BlobPath: /tmp/blobs
UploadPath: /tmp/uploads

ReflectorWorkers: 5
