LbrynetServers:
  default: http://lbrynet:5279/
  lbrynet1: http://lbrynet:5279/
  lbrynet2: http://lbrynet:5279/

Debug: 1

InternalAPIHost: https://api.lbry.com
ProjectURL: https://lbry.tv

DatabaseDSN: postgres://lbrytv:lbrytv@postgres
Database:
  DBName: lbrytv
  Options: sslmode=disable

OAuth:
  ClientID: odysee-apis
  ProviderURL: https://sso.odysee.com/auth/realms/Users
  TokenPath: /protocol/openid-connect/token

PublishSourceDir: /storage/published

PaidTokenPrivKey: token_privkey.rsa

LbrynetXServer: http://sdk.lbry.tech:5279/api
LbrynetXPercentage: 0

FreeContentURL: https://player.odycdn.com/api/v4/streams/free/
PaidContentURL: https://player.odycdn.com/api/v3/streams/paid/

CORSDomains:
  - http://localhost:1337
  - http://localhost:9090

RPCTimeouts:
  txo_spend: 4m
  txo_list: 4m
  transaction_list: 4m
  publish: 4m
