LbrynetServers:
  default: http://lbrynet:5279/
  lbrynet1: http://lbrynet:5279/
  lbrynet2: http://lbrynet:5279/

Debug: 1

BaseContentURL: https://player.odycdn.com/api
FreeContentURL: https://player.odycdn.com/api/v4/streams/free/
PaidContentURL: https://player.odycdn.com/api/v3/streams/paid/

StreamsV5:
  Host: https://player.odycdn.com
  PaidHost: https://secure.odycdn.com
  StartPath: /v5/streams/start
  HLSPath: /v5/streams/hls
  PaidPass: paid-pass

StreamsV6:
  Host: player.odycdn.com
  PaidHost: secure.odycdn.com
  StartPath: /v6/streams/%s/%s.mp4
  Token: cdn-paid-token

InternalAPIHost: https://api.lbry.com
ProjectURL: https://lbry.tv

DatabaseDSN: postgres://postgres:odyseeteam@postgres
Database:
  DBName: postgres
  Options: sslmode=disable

OAuth:
  ClientID: odysee-apis
  ProviderURL: https://sso.odysee.com/auth/realms/Users
  TokenPath: /protocol/openid-connect/token

PublishSourceDir: /storage/published
GeoPublishSourceDir: /storage/geopublish

PaidTokenPrivKey: token_privkey.rsa

# Change this key for production!
# You can re-generate the key by running:
# openssl ecparam -genkey -name prime256v1 -noout -out private_key.pem && base64 -i private_key.pem
UploadTokenPrivateKey: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZZYWxQZkhySzNSQ1F2YmhRQ1h6cDZiWG9uODZWOGI5L3B0bjB3QTZxNkxvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZjhyN3RlQWJwUlVldXZhVWRsNDQzVS9VZkpYZURDd051QkRrbmp5ZnRZaXZ2Tnl6cGt6ZgpYdDl3RE9rc1VZSmEzNVhvSndabjNHMmw2L2EvdVUvWmh3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
UploadServiceURL: http://uploads-v4/v1/

CORSDomains:
  - http://localhost:1337
  - http://localhost:9090

RPCTimeouts:
  txo_spend: 4m
  txo_list: 4m
  transaction_list: 4m
  publish: 4m

RedisLocker: redis://:odyredis@redis:6379/1
RedisBus: redis://:odyredis@redis:6379/2

# AsynqueryRequestsConnURL is Redis database where asynquery will be listening for finalized uploads requests.
# This corresponds to AsynqueryRequestsConnURL in forklift.yml config.
AsynqueryRequestsConnURL: redis://:odyredis@redis:6379/3

SturdyCache:
  Master: redis:6379
  Replicas:
    - redis:6379
  Password: odyredis

ReflectorUpstream:
  DatabaseDSN: 'user:password@tcp(localhost:3306)/blobs'
  Region: us-east-1
  Bucket: blobs'
  Key: key
  Secret: secret

Logging:
  Level: debug
  Format: console
