// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type UploadStatus string

const (
	UploadStatusCreated    UploadStatus = "created"
	UploadStatusReceiving  UploadStatus = "receiving"
	UploadStatusCompleted  UploadStatus = "completed"
	UploadStatusTerminated UploadStatus = "terminated"
	UploadStatusProcessed  UploadStatus = "processed"
)

func (e *UploadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadStatus(s)
	case string:
		*e = UploadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadStatus: %T", src)
	}
	return nil
}

type NullUploadStatus struct {
	UploadStatus UploadStatus
	Valid        bool // Valid is true if UploadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UploadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadStatus), nil
}

type UrlStatus string

const (
	UrlStatusCreated    UrlStatus = "created"
	UrlStatusDownloaded UrlStatus = "downloaded"
	UrlStatusProcessed  UrlStatus = "processed"
)

func (e *UrlStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UrlStatus(s)
	case string:
		*e = UrlStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UrlStatus: %T", src)
	}
	return nil
}

type NullUrlStatus struct {
	UrlStatus UrlStatus
	Valid     bool // Valid is true if UrlStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUrlStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UrlStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UrlStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUrlStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UrlStatus), nil
}

type URL struct {
	ID        string
	UserID    int32
	URL       string
	Filename  string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Status    UrlStatus
	Size      int64
	SDHash    string
	Meta      pqtype.NullRawMessage
}

type Upload struct {
	ID        string
	UserID    int32
	Filename  string
	Key       string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Status    UploadStatus
	Size      int64
	Received  int64
	SDHash    string
	Meta      pqtype.NullRawMessage
}
