swagger: "2.0"
info:
  title: Watchman service
  description: "Watchman collects media playback reports.\n\t\tPlayback time along
    with buffering count and duration is collected\n\t\tvia playback reports, which
    should be sent from the client each n sec\n\t\t(with n being something reasonable
    between 5 and 30s)\n\t"
  version: ""
host: watchman.na-backend.odysee.com
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /healthz:
    get:
      tags:
      - reporter
      summary: healthz reporter
      operationId: reporter#healthz
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - https
  /openapi.json:
    get:
      tags:
      - reporter
      summary: Download ./gen/http/openapi.json
      operationId: reporter#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - https
  /reports/playback:
    post:
      tags:
      - reporter
      summary: add reporter
      operationId: reporter#add
      parameters:
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ReporterAddRequestBody'
          required:
          - url
          - duration
          - position
          - rel_position
          - rebuf_count
          - rebuf_duration
          - protocol
          - player
          - user_id
          - device
      responses:
        "201":
          description: Created response.
      schemes:
      - https
definitions:
  ReporterAddRequestBody:
    title: ReporterAddRequestBody
    type: object
    properties:
      bandwidth:
        type: integer
        description: Client bandwidth, bit/s
        example: 1517669849
        format: int32
      cache:
        type: string
        description: Cache status of video
        example: local
        enum:
        - local
        - player
        - miss
      device:
        type: string
        description: Client device
        example: adr
        enum:
        - ios
        - adr
        - web
      duration:
        type: integer
        description: Duration of time between event calls in ms (aiming for between 5s and 30s so generally 5000 - 3000)
        example: 30000
        minimum: 0
        maximum: 60000
      player:
        type: string
        description: Player server name
        example: sg-p2
        maxLength: 64
      position:
        type: integer
        description: Current playback report stream position, ms
        example: 938401497
        minimum: 0
      protocol:
        type: string
        description: Video delivery protocol, stb (binary stream) or HLS
        example: hls
        enum:
        - stb
        - hls
      rebuf_count:
        type: integer
        description: Rebuffering events count elapsed during the duration
        example: 3
        minimum: 0
      rebuf_duration:
        type: integer
        description: Sum of total rebuffering events durations, ms
        example: 3378
        minimum: 0
        maximum: 60000
      rel_position:
        type: integer
        description: Relative stream position, pct, 0—100
        example: 48
        minimum: 0
        maximum: 100
      url:
        type: string
        description: LBRY URL
        example: what
        maxLength: 512
      user_id:
        type: integer
        description: User ID
        example: 1477881050
        format: int32
    example:
      bandwidth: 830553715
      cache: local
      device: web
      duration: 11291
      player: sg-p2
      position: 263225764
      protocol: stb
      rebuf_count: 1223292224
      rebuf_duration: 12264
      rel_position: 54
      url: what
      user_id: 1422240286
    required:
    - url
    - duration
    - position
    - rel_position
    - rebuf_count
    - rebuf_duration
    - protocol
    - player
    - user_id
    - device
