// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type PlaybackReport struct {
	ID   int32     `json:"id"`
	Time time.Time `json:"time"`
	URL  string    `json:"url"`
	Pos  int32     `json:"pos"`
	Por  int32     `json:"por"`
	Dur  int32     `json:"dur"`
	Bfc  int32     `json:"bfc"`
	Bfd  int32     `json:"bfd"`
	Fmt  string    `json:"fmt"`
	Pid  string    `json:"pid"`
	Cid  string    `json:"cid"`
	Cdv  string    `json:"cdv"`
	Crt  int32     `json:"crt"`
	Car  string    `json:"car"`
}
