name: lint
on:
  push:
    branches:
      - master
      - dev
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          only-new-issues: true
      - id: govulncheck
        uses: golang/govulncheck-action@v1
