name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up containers
        run: docker-compose up -d lbrynet postgres

      - name: Set up containers
        run: docker-compose -f apps/watchman/docker-compose.yml up -d clickhouse geoipupdate

      - name: Check running containers
        run: docker ps -a

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Run go vet
        run: go vet ./...

      - name: Prepare for tests
        run: make prepare_test

      - name: Wait for wallet init
        run: scripts/wait_for_wallet.sh

      - name: Test
        run: |
          go install github.com/jandelgado/gcov2lcov@latest
          go test -covermode=count -coverprofile=coverage.out ./... && gcov2lcov -infile=coverage.out -outfile=coverage.lcov

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: coverage.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
