// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GorpMigrations string
	LbrynetServers string
	QueryLog       string
	UploadQueries  string
	Uploads        string
	Users          string
}{
	GorpMigrations: "gorp_migrations",
	LbrynetServers: "lbrynet_servers",
	QueryLog:       "query_log",
	UploadQueries:  "upload_queries",
	Uploads:        "uploads",
	Users:          "users",
}
