// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Query is an object representing the database table.
type Query struct {
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	Status    string    `boil:"status" json:"status" toml:"status" yaml:"status"`
	Error     string    `boil:"error" json:"error" toml:"error" yaml:"error"`
	Query     null.JSON `boil:"query" json:"query,omitempty" toml:"query" yaml:"query,omitempty"`
	Response  null.JSON `boil:"response" json:"response,omitempty" toml:"response" yaml:"response,omitempty"`
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID    null.Int  `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`

	R *queryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L queryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var QueryColumns = struct {
	CreatedAt string
	UpdatedAt string
	Status    string
	Error     string
	Query     string
	Response  string
	ID        string
	UserID    string
}{
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	Status:    "status",
	Error:     "err",
	Query:     "query",
	Response:  "response",
	ID:        "id",
	UserID:    "user_id",
}

// Generated where

type whereHelpernull_JSON struct{ field string }

func (w whereHelpernull_JSON) EQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_JSON) NEQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_JSON) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_JSON) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }
func (w whereHelpernull_JSON) LT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_JSON) LTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_JSON) GT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_JSON) GTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var QueryWhere = struct {
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpernull_Time
	Status    whereHelperstring
	Error     whereHelperstring
	Query     whereHelpernull_JSON
	Response  whereHelpernull_JSON
	ID        whereHelperint
	UserID    whereHelpernull_Int
}{
	CreatedAt: whereHelpertime_Time{field: "\"queries\".\"created_at\""},
	UpdatedAt: whereHelpernull_Time{field: "\"queries\".\"updated_at\""},
	Status:    whereHelperstring{field: "\"queries\".\"status\""},
	Error:     whereHelperstring{field: "\"queries\".\"error\""},
	Query:     whereHelpernull_JSON{field: "\"queries\".\"query\""},
	Response:  whereHelpernull_JSON{field: "\"queries\".\"response\""},
	ID:        whereHelperint{field: "\"queries\".\"id\""},
	UserID:    whereHelpernull_Int{field: "\"queries\".\"user_id\""},
}

// QueryRels is where relationship names are stored.
var QueryRels = struct {
	User    string
	Uploads string
}{
	User:    "User",
	Uploads: "Uploads",
}

// queryR is where relationships are stored.
type queryR struct {
	User    *User
	Uploads UploadSlice
}

// NewStruct creates a new relationship struct
func (*queryR) NewStruct() *queryR {
	return &queryR{}
}

// queryL is where Load methods for each relationship are stored.
type queryL struct{}

var (
	queryAllColumns            = []string{"created_at", "updated_at", "status", "err", "query", "response", "id", "user_id"}
	queryColumnsWithoutDefault = []string{"updated_at", "status", "err", "query", "response", "user_id"}
	queryColumnsWithDefault    = []string{"created_at", "id"}
	queryPrimaryKeyColumns     = []string{"id"}
)

type (
	// QuerySlice is an alias for a slice of pointers to Query.
	// This should generally be used opposed to []Query.
	QuerySlice []*Query
	// QueryHook is the signature for custom Query hook methods
	QueryHook func(boil.Executor, *Query) error

	queryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	queryType                 = reflect.TypeOf(&Query{})
	queryMapping              = queries.MakeStructMapping(queryType)
	queryPrimaryKeyMapping, _ = queries.BindMapping(queryType, queryMapping, queryPrimaryKeyColumns)
	queryInsertCacheMut       sync.RWMutex
	queryInsertCache          = make(map[string]insertCache)
	queryUpdateCacheMut       sync.RWMutex
	queryUpdateCache          = make(map[string]updateCache)
	queryUpsertCacheMut       sync.RWMutex
	queryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var queryBeforeInsertHooks []QueryHook
var queryBeforeUpdateHooks []QueryHook
var queryBeforeDeleteHooks []QueryHook
var queryBeforeUpsertHooks []QueryHook

var queryAfterInsertHooks []QueryHook
var queryAfterSelectHooks []QueryHook
var queryAfterUpdateHooks []QueryHook
var queryAfterDeleteHooks []QueryHook
var queryAfterUpsertHooks []QueryHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Query) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range queryBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Query) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range queryBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Query) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range queryBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Query) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range queryBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Query) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range queryAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Query) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range queryAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Query) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range queryAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Query) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range queryAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Query) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range queryAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddQueryHook registers your hook function for all future operations.
func AddQueryHook(hookPoint boil.HookPoint, queryHook QueryHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		queryBeforeInsertHooks = append(queryBeforeInsertHooks, queryHook)
	case boil.BeforeUpdateHook:
		queryBeforeUpdateHooks = append(queryBeforeUpdateHooks, queryHook)
	case boil.BeforeDeleteHook:
		queryBeforeDeleteHooks = append(queryBeforeDeleteHooks, queryHook)
	case boil.BeforeUpsertHook:
		queryBeforeUpsertHooks = append(queryBeforeUpsertHooks, queryHook)
	case boil.AfterInsertHook:
		queryAfterInsertHooks = append(queryAfterInsertHooks, queryHook)
	case boil.AfterSelectHook:
		queryAfterSelectHooks = append(queryAfterSelectHooks, queryHook)
	case boil.AfterUpdateHook:
		queryAfterUpdateHooks = append(queryAfterUpdateHooks, queryHook)
	case boil.AfterDeleteHook:
		queryAfterDeleteHooks = append(queryAfterDeleteHooks, queryHook)
	case boil.AfterUpsertHook:
		queryAfterUpsertHooks = append(queryAfterUpsertHooks, queryHook)
	}
}

// OneG returns a single query record from the query using the global executor.
func (q queryQuery) OneG() (*Query, error) {
	return q.One(boil.GetDB())
}

// One returns a single query record from the query.
func (q queryQuery) One(exec boil.Executor) (*Query, error) {
	o := &Query{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for queries")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Query records from the query using the global executor.
func (q queryQuery) AllG() (QuerySlice, error) {
	return q.All(boil.GetDB())
}

// All returns all Query records from the query.
func (q queryQuery) All(exec boil.Executor) (QuerySlice, error) {
	var o []*Query

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Query slice")
	}

	if len(queryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Query records in the query, and panics on error.
func (q queryQuery) CountG() (int64, error) {
	return q.Count(boil.GetDB())
}

// Count returns the count of all Query records in the query.
func (q queryQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count queries rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table, and panics on error.
func (q queryQuery) ExistsG() (bool, error) {
	return q.Exists(boil.GetDB())
}

// Exists checks if the row exists in the table.
func (q queryQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if queries exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *Query) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// Uploads retrieves all the upload's Uploads with an executor.
func (o *Query) Uploads(mods ...qm.QueryMod) uploadQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"uploads\".\"query_id\"=?", o.ID),
	)

	query := Uploads(queryMods...)
	queries.SetFrom(query.Query, "\"uploads\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"uploads\".*"})
	}

	return query
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (queryL) LoadUser(e boil.Executor, singular bool, maybeQuery interface{}, mods queries.Applicator) error {
	var slice []*Query
	var object *Query

	if singular {
		object = maybeQuery.(*Query)
	} else {
		slice = *maybeQuery.(*[]*Query)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &queryR{}
		}
		if !queries.IsNil(object.UserID) {
			args = append(args, object.UserID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &queryR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.UserID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.UserID) {
				args = append(args, obj.UserID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`users`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(queryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.Queries = append(foreign.R.Queries, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserID, foreign.ID) {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Queries = append(foreign.R.Queries, local)
				break
			}
		}
	}

	return nil
}

// LoadUploads allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (queryL) LoadUploads(e boil.Executor, singular bool, maybeQuery interface{}, mods queries.Applicator) error {
	var slice []*Query
	var object *Query

	if singular {
		object = maybeQuery.(*Query)
	} else {
		slice = *maybeQuery.(*[]*Query)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &queryR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &queryR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`uploads`), qm.WhereIn(`query_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load uploads")
	}

	var resultSlice []*Upload
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice uploads")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on uploads")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for uploads")
	}

	if len(uploadAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Uploads = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &uploadR{}
			}
			foreign.R.Query = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.QueryID) {
				local.R.Uploads = append(local.R.Uploads, foreign)
				if foreign.R == nil {
					foreign.R = &uploadR{}
				}
				foreign.R.Query = local
				break
			}
		}
	}

	return nil
}

// SetUserG of the query to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Queries.
// Uses the global database handle.
func (o *Query) SetUserG(insert bool, related *User) error {
	return o.SetUser(boil.GetDB(), insert, related)
}

// SetUser of the query to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Queries.
func (o *Query) SetUser(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"queries\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, queryPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserID, related.ID)
	if o.R == nil {
		o.R = &queryR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Queries: QuerySlice{o},
		}
	} else {
		related.R.Queries = append(related.R.Queries, o)
	}

	return nil
}

// RemoveUserG relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle.
func (o *Query) RemoveUserG(related *User) error {
	return o.RemoveUser(boil.GetDB(), related)
}

// RemoveUser relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *Query) RemoveUser(exec boil.Executor, related *User) error {
	var err error

	queries.SetScanner(&o.UserID, nil)
	if _, err = o.Update(exec, boil.Whitelist("user_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.User = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Queries {
		if queries.Equal(o.UserID, ri.UserID) {
			continue
		}

		ln := len(related.R.Queries)
		if ln > 1 && i < ln-1 {
			related.R.Queries[i] = related.R.Queries[ln-1]
		}
		related.R.Queries = related.R.Queries[:ln-1]
		break
	}
	return nil
}

// AddUploadsG adds the given related objects to the existing relationships
// of the query, optionally inserting them as new records.
// Appends related to o.R.Uploads.
// Sets related.R.Query appropriately.
// Uses the global database handle.
func (o *Query) AddUploadsG(insert bool, related ...*Upload) error {
	return o.AddUploads(boil.GetDB(), insert, related...)
}

// AddUploads adds the given related objects to the existing relationships
// of the query, optionally inserting them as new records.
// Appends related to o.R.Uploads.
// Sets related.R.Query appropriately.
func (o *Query) AddUploads(exec boil.Executor, insert bool, related ...*Upload) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.QueryID, o.ID)
			if err = rel.Insert(exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"uploads\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"query_id"}),
				strmangle.WhereClause("\"", "\"", 2, uploadPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.QueryID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &queryR{
			Uploads: related,
		}
	} else {
		o.R.Uploads = append(o.R.Uploads, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &uploadR{
				Query: o,
			}
		} else {
			rel.R.Query = o
		}
	}
	return nil
}

// SetUploadsG removes all previously related items of the
// query replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Query's Uploads accordingly.
// Replaces o.R.Uploads with related.
// Sets related.R.Query's Uploads accordingly.
// Uses the global database handle.
func (o *Query) SetUploadsG(insert bool, related ...*Upload) error {
	return o.SetUploads(boil.GetDB(), insert, related...)
}

// SetUploads removes all previously related items of the
// query replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Query's Uploads accordingly.
// Replaces o.R.Uploads with related.
// Sets related.R.Query's Uploads accordingly.
func (o *Query) SetUploads(exec boil.Executor, insert bool, related ...*Upload) error {
	query := "update \"uploads\" set \"query_id\" = null where \"query_id\" = $1"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.Uploads {
			queries.SetScanner(&rel.QueryID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Query = nil
		}

		o.R.Uploads = nil
	}
	return o.AddUploads(exec, insert, related...)
}

// RemoveUploadsG relationships from objects passed in.
// Removes related items from R.Uploads (uses pointer comparison, removal does not keep order)
// Sets related.R.Query.
// Uses the global database handle.
func (o *Query) RemoveUploadsG(related ...*Upload) error {
	return o.RemoveUploads(boil.GetDB(), related...)
}

// RemoveUploads relationships from objects passed in.
// Removes related items from R.Uploads (uses pointer comparison, removal does not keep order)
// Sets related.R.Query.
func (o *Query) RemoveUploads(exec boil.Executor, related ...*Upload) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.QueryID, nil)
		if rel.R != nil {
			rel.R.Query = nil
		}
		if _, err = rel.Update(exec, boil.Whitelist("query_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Uploads {
			if rel != ri {
				continue
			}

			ln := len(o.R.Uploads)
			if ln > 1 && i < ln-1 {
				o.R.Uploads[i] = o.R.Uploads[ln-1]
			}
			o.R.Uploads = o.R.Uploads[:ln-1]
			break
		}
	}

	return nil
}

// Queries retrieves all the records using an executor.
func Queries(mods ...qm.QueryMod) queryQuery {
	mods = append(mods, qm.From("\"queries\""))
	return queryQuery{NewQuery(mods...)}
}

// FindQueryG retrieves a single record by ID.
func FindQueryG(iD int, selectCols ...string) (*Query, error) {
	return FindQuery(boil.GetDB(), iD, selectCols...)
}

// FindQuery retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindQuery(exec boil.Executor, iD int, selectCols ...string) (*Query, error) {
	queryObj := &Query{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"queries\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, queryObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from queries")
	}

	return queryObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Query) InsertG(columns boil.Columns) error {
	return o.Insert(boil.GetDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Query) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no queries provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if queries.MustTime(o.UpdatedAt).IsZero() {
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(queryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	queryInsertCacheMut.RLock()
	cache, cached := queryInsertCache[key]
	queryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			queryAllColumns,
			queryColumnsWithDefault,
			queryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(queryType, queryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(queryType, queryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"queries\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"queries\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into queries")
	}

	if !cached {
		queryInsertCacheMut.Lock()
		queryInsertCache[key] = cache
		queryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Query record using the global executor.
// See Update for more documentation.
func (o *Query) UpdateG(columns boil.Columns) (int64, error) {
	return o.Update(boil.GetDB(), columns)
}

// Update uses an executor to update the Query.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Query) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	queries.SetScanner(&o.UpdatedAt, currTime)

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	queryUpdateCacheMut.RLock()
	cache, cached := queryUpdateCache[key]
	queryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			queryAllColumns,
			queryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update queries, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"queries\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, queryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(queryType, queryMapping, append(wl, queryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update queries row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for queries")
	}

	if !cached {
		queryUpdateCacheMut.Lock()
		queryUpdateCache[key] = cache
		queryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q queryQuery) UpdateAllG(cols M) (int64, error) {
	return q.UpdateAll(boil.GetDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q queryQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for queries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for queries")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o QuerySlice) UpdateAllG(cols M) (int64, error) {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o QuerySlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), queryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"queries\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, queryPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in query slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all query")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Query) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Query) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no queries provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	queries.SetScanner(&o.UpdatedAt, currTime)

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(queryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	queryUpsertCacheMut.RLock()
	cache, cached := queryUpsertCache[key]
	queryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			queryAllColumns,
			queryColumnsWithDefault,
			queryColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			queryAllColumns,
			queryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert queries, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(queryPrimaryKeyColumns))
			copy(conflict, queryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"queries\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(queryType, queryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(queryType, queryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert queries")
	}

	if !cached {
		queryUpsertCacheMut.Lock()
		queryUpsertCache[key] = cache
		queryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteG deletes a single Query record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Query) DeleteG() (int64, error) {
	return o.Delete(boil.GetDB())
}

// Delete deletes a single Query record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Query) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Query provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), queryPrimaryKeyMapping)
	sql := "DELETE FROM \"queries\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from queries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for queries")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q queryQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no queryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from queries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for queries")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o QuerySlice) DeleteAllG() (int64, error) {
	return o.DeleteAll(boil.GetDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o QuerySlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(queryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), queryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"queries\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, queryPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from query slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for queries")
	}

	if len(queryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Query) ReloadG() error {
	if o == nil {
		return errors.New("models: no Query provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Query) Reload(exec boil.Executor) error {
	ret, err := FindQuery(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *QuerySlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty QuerySlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *QuerySlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := QuerySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), queryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"queries\".* FROM \"queries\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, queryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in QuerySlice")
	}

	*o = slice

	return nil
}

// QueryExistsG checks if the Query row exists.
func QueryExistsG(iD int) (bool, error) {
	return QueryExists(boil.GetDB(), iD)
}

// QueryExists checks if the Query row exists.
func QueryExists(exec boil.Executor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"queries\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if queries exists")
	}

	return exists, nil
}
