// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// SDKReconnectLease is an object representing the database table.
type SDKReconnectLease struct {
	LeaseKey             string      `boil:"lease_key" json:"lease_key" toml:"lease_key" yaml:"lease_key"`
	LeaseKind            string      `boil:"lease_kind" json:"lease_kind" toml:"lease_kind" yaml:"lease_kind"`
	Owner                null.String `boil:"owner" json:"owner,omitempty" toml:"owner" yaml:"owner,omitempty"`
	LeaseExpiresAt       null.Time   `boil:"lease_expires_at" json:"lease_expires_at,omitempty" toml:"lease_expires_at" yaml:"lease_expires_at,omitempty"`
	LastReconnectAt      null.Time   `boil:"last_reconnect_at" json:"last_reconnect_at,omitempty" toml:"last_reconnect_at" yaml:"last_reconnect_at,omitempty"`
	MaxAttemptsAlertedAt null.Time   `boil:"max_attempts_alerted_at" json:"max_attempts_alerted_at,omitempty" toml:"max_attempts_alerted_at" yaml:"max_attempts_alerted_at,omitempty"`
	Attempts             int         `boil:"attempts" json:"attempts" toml:"attempts" yaml:"attempts"`
	UpdatedAt            time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *sdkReconnectLeaseR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L sdkReconnectLeaseL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SDKReconnectLeaseColumns = struct {
	LeaseKey             string
	LeaseKind            string
	Owner                string
	LeaseExpiresAt       string
	LastReconnectAt      string
	MaxAttemptsAlertedAt string
	Attempts             string
	UpdatedAt            string
}{
	LeaseKey:             "lease_key",
	LeaseKind:            "lease_kind",
	Owner:                "owner",
	LeaseExpiresAt:       "lease_expires_at",
	LastReconnectAt:      "last_reconnect_at",
	MaxAttemptsAlertedAt: "max_attempts_alerted_at",
	Attempts:             "attempts",
	UpdatedAt:            "updated_at",
}

var SDKReconnectLeaseTableColumns = struct {
	LeaseKey             string
	LeaseKind            string
	Owner                string
	LeaseExpiresAt       string
	LastReconnectAt      string
	MaxAttemptsAlertedAt string
	Attempts             string
	UpdatedAt            string
}{
	LeaseKey:             "sdk_reconnect_leases.lease_key",
	LeaseKind:            "sdk_reconnect_leases.lease_kind",
	Owner:                "sdk_reconnect_leases.owner",
	LeaseExpiresAt:       "sdk_reconnect_leases.lease_expires_at",
	LastReconnectAt:      "sdk_reconnect_leases.last_reconnect_at",
	MaxAttemptsAlertedAt: "sdk_reconnect_leases.max_attempts_alerted_at",
	Attempts:             "sdk_reconnect_leases.attempts",
	UpdatedAt:            "sdk_reconnect_leases.updated_at",
}

var SDKReconnectLeaseWhere = struct {
	LeaseKey             whereHelperstring
	LeaseKind            whereHelperstring
	Owner                whereHelpernull_String
	LeaseExpiresAt       whereHelpernull_Time
	LastReconnectAt      whereHelpernull_Time
	MaxAttemptsAlertedAt whereHelpernull_Time
	Attempts             whereHelperint
	UpdatedAt            whereHelpertime_Time
}{
	LeaseKey:             whereHelperstring{field: "\"sdk_reconnect_leases\".\"lease_key\""},
	LeaseKind:            whereHelperstring{field: "\"sdk_reconnect_leases\".\"lease_kind\""},
	Owner:                whereHelpernull_String{field: "\"sdk_reconnect_leases\".\"owner\""},
	LeaseExpiresAt:       whereHelpernull_Time{field: "\"sdk_reconnect_leases\".\"lease_expires_at\""},
	LastReconnectAt:      whereHelpernull_Time{field: "\"sdk_reconnect_leases\".\"last_reconnect_at\""},
	MaxAttemptsAlertedAt: whereHelpernull_Time{field: "\"sdk_reconnect_leases\".\"max_attempts_alerted_at\""},
	Attempts:             whereHelperint{field: "\"sdk_reconnect_leases\".\"attempts\""},
	UpdatedAt:            whereHelpertime_Time{field: "\"sdk_reconnect_leases\".\"updated_at\""},
}

// SDKReconnectLeaseRels is where relationship names are stored.
var SDKReconnectLeaseRels = struct {
}{}

// sdkReconnectLeaseR is where relationships are stored.
type sdkReconnectLeaseR struct {
}

// NewStruct creates a new relationship struct
func (*sdkReconnectLeaseR) NewStruct() *sdkReconnectLeaseR {
	return &sdkReconnectLeaseR{}
}

// sdkReconnectLeaseL is where Load methods for each relationship are stored.
type sdkReconnectLeaseL struct{}

var (
	sdkReconnectLeaseAllColumns            = []string{"lease_key", "lease_kind", "owner", "lease_expires_at", "last_reconnect_at", "max_attempts_alerted_at", "attempts", "updated_at"}
	sdkReconnectLeaseColumnsWithoutDefault = []string{"lease_key", "lease_kind", "owner", "lease_expires_at", "last_reconnect_at", "max_attempts_alerted_at"}
	sdkReconnectLeaseColumnsWithDefault    = []string{"attempts", "updated_at"}
	sdkReconnectLeasePrimaryKeyColumns     = []string{"lease_key"}
	sdkReconnectLeaseGeneratedColumns      = []string{}
)

type (
	// SDKReconnectLeaseSlice is an alias for a slice of pointers to SDKReconnectLease.
	// This should almost always be used instead of []SDKReconnectLease.
	SDKReconnectLeaseSlice []*SDKReconnectLease
	// SDKReconnectLeaseHook is the signature for custom SDKReconnectLease hook methods
	SDKReconnectLeaseHook func(boil.Executor, *SDKReconnectLease) error

	sdkReconnectLeaseQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	sdkReconnectLeaseType                 = reflect.TypeOf(&SDKReconnectLease{})
	sdkReconnectLeaseMapping              = queries.MakeStructMapping(sdkReconnectLeaseType)
	sdkReconnectLeasePrimaryKeyMapping, _ = queries.BindMapping(sdkReconnectLeaseType, sdkReconnectLeaseMapping, sdkReconnectLeasePrimaryKeyColumns)
	sdkReconnectLeaseInsertCacheMut       sync.RWMutex
	sdkReconnectLeaseInsertCache          = make(map[string]insertCache)
	sdkReconnectLeaseUpdateCacheMut       sync.RWMutex
	sdkReconnectLeaseUpdateCache          = make(map[string]updateCache)
	sdkReconnectLeaseUpsertCacheMut       sync.RWMutex
	sdkReconnectLeaseUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
)

var sdkReconnectLeaseAfterSelectMu sync.Mutex
var sdkReconnectLeaseAfterSelectHooks []SDKReconnectLeaseHook

var sdkReconnectLeaseBeforeInsertMu sync.Mutex
var sdkReconnectLeaseBeforeInsertHooks []SDKReconnectLeaseHook
var sdkReconnectLeaseAfterInsertMu sync.Mutex
var sdkReconnectLeaseAfterInsertHooks []SDKReconnectLeaseHook

var sdkReconnectLeaseBeforeUpdateMu sync.Mutex
var sdkReconnectLeaseBeforeUpdateHooks []SDKReconnectLeaseHook
var sdkReconnectLeaseAfterUpdateMu sync.Mutex
var sdkReconnectLeaseAfterUpdateHooks []SDKReconnectLeaseHook

var sdkReconnectLeaseBeforeDeleteMu sync.Mutex
var sdkReconnectLeaseBeforeDeleteHooks []SDKReconnectLeaseHook
var sdkReconnectLeaseAfterDeleteMu sync.Mutex
var sdkReconnectLeaseAfterDeleteHooks []SDKReconnectLeaseHook

var sdkReconnectLeaseBeforeUpsertMu sync.Mutex
var sdkReconnectLeaseBeforeUpsertHooks []SDKReconnectLeaseHook
var sdkReconnectLeaseAfterUpsertMu sync.Mutex
var sdkReconnectLeaseAfterUpsertHooks []SDKReconnectLeaseHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SDKReconnectLease) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range sdkReconnectLeaseAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SDKReconnectLease) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range sdkReconnectLeaseBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SDKReconnectLease) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range sdkReconnectLeaseAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SDKReconnectLease) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range sdkReconnectLeaseBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SDKReconnectLease) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range sdkReconnectLeaseAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SDKReconnectLease) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range sdkReconnectLeaseBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SDKReconnectLease) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range sdkReconnectLeaseAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SDKReconnectLease) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range sdkReconnectLeaseBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SDKReconnectLease) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range sdkReconnectLeaseAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSDKReconnectLeaseHook registers your hook function for all future operations.
func AddSDKReconnectLeaseHook(hookPoint boil.HookPoint, sdkReconnectLeaseHook SDKReconnectLeaseHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		sdkReconnectLeaseAfterSelectMu.Lock()
		sdkReconnectLeaseAfterSelectHooks = append(sdkReconnectLeaseAfterSelectHooks, sdkReconnectLeaseHook)
		sdkReconnectLeaseAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		sdkReconnectLeaseBeforeInsertMu.Lock()
		sdkReconnectLeaseBeforeInsertHooks = append(sdkReconnectLeaseBeforeInsertHooks, sdkReconnectLeaseHook)
		sdkReconnectLeaseBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		sdkReconnectLeaseAfterInsertMu.Lock()
		sdkReconnectLeaseAfterInsertHooks = append(sdkReconnectLeaseAfterInsertHooks, sdkReconnectLeaseHook)
		sdkReconnectLeaseAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		sdkReconnectLeaseBeforeUpdateMu.Lock()
		sdkReconnectLeaseBeforeUpdateHooks = append(sdkReconnectLeaseBeforeUpdateHooks, sdkReconnectLeaseHook)
		sdkReconnectLeaseBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		sdkReconnectLeaseAfterUpdateMu.Lock()
		sdkReconnectLeaseAfterUpdateHooks = append(sdkReconnectLeaseAfterUpdateHooks, sdkReconnectLeaseHook)
		sdkReconnectLeaseAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		sdkReconnectLeaseBeforeDeleteMu.Lock()
		sdkReconnectLeaseBeforeDeleteHooks = append(sdkReconnectLeaseBeforeDeleteHooks, sdkReconnectLeaseHook)
		sdkReconnectLeaseBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		sdkReconnectLeaseAfterDeleteMu.Lock()
		sdkReconnectLeaseAfterDeleteHooks = append(sdkReconnectLeaseAfterDeleteHooks, sdkReconnectLeaseHook)
		sdkReconnectLeaseAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		sdkReconnectLeaseBeforeUpsertMu.Lock()
		sdkReconnectLeaseBeforeUpsertHooks = append(sdkReconnectLeaseBeforeUpsertHooks, sdkReconnectLeaseHook)
		sdkReconnectLeaseBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		sdkReconnectLeaseAfterUpsertMu.Lock()
		sdkReconnectLeaseAfterUpsertHooks = append(sdkReconnectLeaseAfterUpsertHooks, sdkReconnectLeaseHook)
		sdkReconnectLeaseAfterUpsertMu.Unlock()
	}
}

// OneG returns a single sdkReconnectLease record from the query using the global executor.
func (q sdkReconnectLeaseQuery) OneG() (*SDKReconnectLease, error) {
	return q.One(boil.GetDB())
}

// One returns a single sdkReconnectLease record from the query.
func (q sdkReconnectLeaseQuery) One(exec boil.Executor) (*SDKReconnectLease, error) {
	o := &SDKReconnectLease{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for sdk_reconnect_leases")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all SDKReconnectLease records from the query using the global executor.
func (q sdkReconnectLeaseQuery) AllG() (SDKReconnectLeaseSlice, error) {
	return q.All(boil.GetDB())
}

// All returns all SDKReconnectLease records from the query.
func (q sdkReconnectLeaseQuery) All(exec boil.Executor) (SDKReconnectLeaseSlice, error) {
	var o []*SDKReconnectLease

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SDKReconnectLease slice")
	}

	if len(sdkReconnectLeaseAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all SDKReconnectLease records in the query using the global executor
func (q sdkReconnectLeaseQuery) CountG() (int64, error) {
	return q.Count(boil.GetDB())
}

// Count returns the count of all SDKReconnectLease records in the query.
func (q sdkReconnectLeaseQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count sdk_reconnect_leases rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q sdkReconnectLeaseQuery) ExistsG() (bool, error) {
	return q.Exists(boil.GetDB())
}

// Exists checks if the row exists in the table.
func (q sdkReconnectLeaseQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if sdk_reconnect_leases exists")
	}

	return count > 0, nil
}

// SDKReconnectLeases retrieves all the records using an executor.
func SDKReconnectLeases(mods ...qm.QueryMod) sdkReconnectLeaseQuery {
	mods = append(mods, qm.From("\"sdk_reconnect_leases\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"sdk_reconnect_leases\".*"})
	}

	return sdkReconnectLeaseQuery{q}
}

// FindSDKReconnectLeaseG retrieves a single record by ID.
func FindSDKReconnectLeaseG(leaseKey string, selectCols ...string) (*SDKReconnectLease, error) {
	return FindSDKReconnectLease(boil.GetDB(), leaseKey, selectCols...)
}

// FindSDKReconnectLease retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSDKReconnectLease(exec boil.Executor, leaseKey string, selectCols ...string) (*SDKReconnectLease, error) {
	sdkReconnectLeaseObj := &SDKReconnectLease{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"sdk_reconnect_leases\" where \"lease_key\"=$1", sel,
	)

	q := queries.Raw(query, leaseKey)

	err := q.Bind(nil, exec, sdkReconnectLeaseObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from sdk_reconnect_leases")
	}

	if err = sdkReconnectLeaseObj.doAfterSelectHooks(exec); err != nil {
		return sdkReconnectLeaseObj, err
	}

	return sdkReconnectLeaseObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *SDKReconnectLease) InsertG(columns boil.Columns) error {
	return o.Insert(boil.GetDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SDKReconnectLease) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no sdk_reconnect_leases provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sdkReconnectLeaseColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	sdkReconnectLeaseInsertCacheMut.RLock()
	cache, cached := sdkReconnectLeaseInsertCache[key]
	sdkReconnectLeaseInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			sdkReconnectLeaseAllColumns,
			sdkReconnectLeaseColumnsWithDefault,
			sdkReconnectLeaseColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(sdkReconnectLeaseType, sdkReconnectLeaseMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(sdkReconnectLeaseType, sdkReconnectLeaseMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"sdk_reconnect_leases\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"sdk_reconnect_leases\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into sdk_reconnect_leases")
	}

	if !cached {
		sdkReconnectLeaseInsertCacheMut.Lock()
		sdkReconnectLeaseInsertCache[key] = cache
		sdkReconnectLeaseInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single SDKReconnectLease record using the global executor.
// See Update for more documentation.
func (o *SDKReconnectLease) UpdateG(columns boil.Columns) (int64, error) {
	return o.Update(boil.GetDB(), columns)
}

// Update uses an executor to update the SDKReconnectLease.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SDKReconnectLease) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	sdkReconnectLeaseUpdateCacheMut.RLock()
	cache, cached := sdkReconnectLeaseUpdateCache[key]
	sdkReconnectLeaseUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			sdkReconnectLeaseAllColumns,
			sdkReconnectLeasePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update sdk_reconnect_leases, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"sdk_reconnect_leases\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, sdkReconnectLeasePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(sdkReconnectLeaseType, sdkReconnectLeaseMapping, append(wl, sdkReconnectLeasePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update sdk_reconnect_leases row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for sdk_reconnect_leases")
	}

	if !cached {
		sdkReconnectLeaseUpdateCacheMut.Lock()
		sdkReconnectLeaseUpdateCache[key] = cache
		sdkReconnectLeaseUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q sdkReconnectLeaseQuery) UpdateAllG(cols M) (int64, error) {
	return q.UpdateAll(boil.GetDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q sdkReconnectLeaseQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for sdk_reconnect_leases")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for sdk_reconnect_leases")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o SDKReconnectLeaseSlice) UpdateAllG(cols M) (int64, error) {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SDKReconnectLeaseSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sdkReconnectLeasePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"sdk_reconnect_leases\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, sdkReconnectLeasePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in sdkReconnectLease slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all sdkReconnectLease")
	}
	return rowsAff, nil
}

// DeleteG deletes a single SDKReconnectLease record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *SDKReconnectLease) DeleteG() (int64, error) {
	return o.Delete(boil.GetDB())
}

// Delete deletes a single SDKReconnectLease record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SDKReconnectLease) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SDKReconnectLease provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), sdkReconnectLeasePrimaryKeyMapping)
	sql := "DELETE FROM \"sdk_reconnect_leases\" WHERE \"lease_key\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from sdk_reconnect_leases")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for sdk_reconnect_leases")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q sdkReconnectLeaseQuery) DeleteAllG() (int64, error) {
	return q.DeleteAll(boil.GetDB())
}

// DeleteAll deletes all matching rows.
func (q sdkReconnectLeaseQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no sdkReconnectLeaseQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from sdk_reconnect_leases")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for sdk_reconnect_leases")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o SDKReconnectLeaseSlice) DeleteAllG() (int64, error) {
	return o.DeleteAll(boil.GetDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SDKReconnectLeaseSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(sdkReconnectLeaseBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sdkReconnectLeasePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"sdk_reconnect_leases\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, sdkReconnectLeasePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from sdkReconnectLease slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for sdk_reconnect_leases")
	}

	if len(sdkReconnectLeaseAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *SDKReconnectLease) ReloadG() error {
	if o == nil {
		return errors.New("models: no SDKReconnectLease provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SDKReconnectLease) Reload(exec boil.Executor) error {
	ret, err := FindSDKReconnectLease(exec, o.LeaseKey)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SDKReconnectLeaseSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty SDKReconnectLeaseSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SDKReconnectLeaseSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SDKReconnectLeaseSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sdkReconnectLeasePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"sdk_reconnect_leases\".* FROM \"sdk_reconnect_leases\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, sdkReconnectLeasePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SDKReconnectLeaseSlice")
	}

	*o = slice

	return nil
}

// SDKReconnectLeaseExistsG checks if the SDKReconnectLease row exists.
func SDKReconnectLeaseExistsG(leaseKey string) (bool, error) {
	return SDKReconnectLeaseExists(boil.GetDB(), leaseKey)
}

// SDKReconnectLeaseExists checks if the SDKReconnectLease row exists.
func SDKReconnectLeaseExists(exec boil.Executor, leaseKey string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"sdk_reconnect_leases\" where \"lease_key\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, leaseKey)
	}
	row := exec.QueryRow(sql, leaseKey)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if sdk_reconnect_leases exists")
	}

	return exists, nil
}

// Exists checks if the SDKReconnectLease row exists.
func (o *SDKReconnectLease) Exists(exec boil.Executor) (bool, error) {
	return SDKReconnectLeaseExists(exec, o.LeaseKey)
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *SDKReconnectLease) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SDKReconnectLease) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no sdk_reconnect_leases provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sdkReconnectLeaseColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	sdkReconnectLeaseUpsertCacheMut.RLock()
	cache, cached := sdkReconnectLeaseUpsertCache[key]
	sdkReconnectLeaseUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			sdkReconnectLeaseAllColumns,
			sdkReconnectLeaseColumnsWithDefault,
			sdkReconnectLeaseColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			sdkReconnectLeaseAllColumns,
			sdkReconnectLeasePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert sdk_reconnect_leases, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(sdkReconnectLeasePrimaryKeyColumns))
			copy(conflict, sdkReconnectLeasePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"sdk_reconnect_leases\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(sdkReconnectLeaseType, sdkReconnectLeaseMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(sdkReconnectLeaseType, sdkReconnectLeaseMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert sdk_reconnect_leases")
	}

	if !cached {
		sdkReconnectLeaseUpsertCacheMut.Lock()
		sdkReconnectLeaseUpsertCache[key] = cache
		sdkReconnectLeaseUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}
